"""add user role enum constraint

Revision ID: d704e349dc90
Revises: 0f2fd3b779e7
Create Date: 2026-04-16 16:46:25.965219

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d704e349dc90"
down_revision: Union[str, Sequence[str], None] = "0f2fd3b779e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала обновляем данные на валидные значения для нового ENUM
    op.execute(
        "UPDATE users SET role = 'client' WHERE role NOT IN ('admin', 'staff', 'client')"
    )

    # Создаём ENUM тип
    userrole_enum = sa.Enum("admin", "staff", "client", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Меняем колонку на ENUM
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        type_=userrole_enum,
        existing_nullable=False,
        postgresql_using="role::text::userrole",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum("admin", "staff", "client", name="userrole"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        postgresql_using="role::text",
    )

    # Удаляем ENUM тип
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
